### ISSUE TITLE
Move to another platform

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#12]
Because SmarterAsp.net's deployment options are bad.

We need:

1. Web App hosting - windows or linux
2. MSSQL Database

**Comment by benjaminsampica** [comment]
We got everything setup in Azure then decided not to because development has slowed down and this just isn’t an issue anymore with the pace.

**Comment by benjaminsampica** [comment]
Site is down until this work is done.

**Comment by Lyddon7522** [comment]
Site is down 😂
