### ISSUE TITLE
Auto Bidding feature

### ISSUE THREAD

**Issue by sd0408** [benjaminsampica/DynamoLeagueBlazor#136]
As a team owner I would like to be able to select a player during free agency and set a maximum price that I would pay for that player. Then when any other owner bids on that player and their bid is less than my maximum, I would like the system to automatically outbid that other owner. If two owners utilize this feature on the same player the owner who sets the higher number would end up with the highest bid and that bid would be 1 more than the other owner's highest bid. This feature should not replace standard bidding and if I set a max bid I can still manually go over that max bid, but it would render my max bid useless.

**Comment by benjaminsampica** [comment]
When a team is outbid immediately by a counter bid that exceeds their bid we should make sure the user experience is obvious that they’ve _already_ been outbid.
