### ISSUE TITLE
Adjust title headers on tables

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#15]
Currently a little squashed on mobile
Center the search bar on mobile

**Comment by morkusporkus** [comment]
Is sortable doable?

**Comment by benjaminsampica** [comment]
Clarified the ask but curious about ur ask

**Comment by Lyddon7522** [comment]
I believe he is asking to be able to sort on the column headers, which is possible using [<MudTableSortLabel>](https://mudblazor.com/components/table#sorting) on the headers
