### ISSUE TITLE
Facilitate the rookie draft

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#156]
- Chat-room esque interaction where the moderator can put a rookie up for bid.
- Everyone in the room can bid up to their remaining cap space
- Upon bidding closing, that player is immediately given to the team and cap space is updated in real-time.

Outstanding questions:
1. Do they get the opportunity to sign a contract like normal players?
2. How should the moderator “staging” of players look/feel for the moderator as well as the players?
3. Assume everyone is in-person? actively participating remotely? 

Additional thoughts:
- Updating existing rules which penalize players for overbidding. This shouldn’t be possible if it’s in the application.
- Should use the exact same bidding logic that currently exists, with the moderator able to end bidding immediately and send the player to the team’s roster.
- Using a SignalR hub will likely be easiest to implement.

**Comment by morkusporkus** [comment]
1. Yes, they are treated the same.  If the player is an actual rookie they can be signed for an additional year
2. Admin could have a slot to add draft players. Idk yet
3. remotely

**Comment by morkusporkus** [comment]
Currently for yahoo
Players are nominated team by team
