### ISSUE TITLE
Add a way to manage next years draft picks 

### ISSUE THREAD

**Issue by morkusporkus** [benjaminsampica/DynamoLeagueBlazor#175]
The league is changing to a standard draft. With this the teams are able to trade draft picks for players.

**Comment by benjaminsampica** [comment]
Questions:

what is the timing of draft picks being chosen? After the end of all free agencies?

this will need to happen on or before draft facilitation? Could it happen as part of draft facilitation or should it have a tail up and to the actual rookie draft?

what’s your vision for how trading happens?

I imagine this will determine the order for the draft?
