### ISSUE TITLE
Center and reduce padding on `Top` dashboard items

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#178]
![Screenshot_20221123-212647](https://user-images.githubusercontent.com/25310886/203689181-8a2c77fb-2020-4888-b866-46ba2d904437.png)

**Comment by HenryMigo** [comment]
@benjaminsampica I can pick this up, but from a brief play and looking at the Mud Blazor Docs I am unsure if the centering of the last item is possible. I can at least tackle the spacing issue though!

**Comment by benjaminsampica** [comment]
@HenryMigo Thanks again!

**Comment by HenryMigo** [comment]
No worries glad to actually do some contributing!
