### ISSUE TITLE
Improve developer experience for application cold boot around docker images being initialized.

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#183]
See #179.

> The sql server image is large so the first-time boot is really slow locally. This needs to surface somehow to make it more obvious docker is doing its thing without it being tribal knowledge.

Could be adding a wiki and linking to it via the README or more clever with the application itself.

**Comment by HenryMigo** [comment]
@benjaminsampica I have added some documentation for this. I have also referenced to the other issue that the process improvement or surfacing of what's going on is known as an issue.

**Comment by benjaminsampica** [comment]
Found this… https://dotnet.testcontainers.org/api/wait_strategies/

will investigate this further.
