### ISSUE TITLE
Connect with yahoo API for transactions. 

### ISSUE THREAD

**Issue by morkusporkus** [benjaminsampica/DynamoLeagueBlazor#32]

**Comment by benjaminsampica** [comment]
https://developer.yahoo.com/fantasysports/guide/#transaction-resource

Solution

1. Use your username/password or a smurf account that sits in the league.
2. Use an utility to automate logging in with the account to grab an access token. (Playwright likely)
3. Run the job daily. Turn off job when the league is offline.
  - Job should store completed trades, waivers, and pending trades
5. Create more cards around surfacing that information and/or acting upon it.
