### ISSUE TITLE
Associate fines with teams

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#51]
Currently fines are only associated with players. We need to associate these with the team the player is rostered under the moment the fine is approved. This is in order to properly fine the correct team (in case the player is traded) and provide roll-up data for a teams’ total fines.

We will need to reconcile existing fines? Remove them and start new? Nullable teamId? @morkusporkus

**Comment by morkusporkus** [comment]
We will not need to reconcile existing fines @benjaminsampica, I am already reconciling them manually, just a kinda a burden at the moment.

**Comment by benjaminsampica** [comment]
Would be cool to show everyone’s fine totals on the dashboard too as a way to name & shame, IMO. That can either be tackled here or as a new issue.
