### ISSUE TITLE
Sorting/Ordering is unclear on mobile

### ISSUE THREAD

**Issue by benjaminsampica** [benjaminsampica/DynamoLeagueBlazor#81]
![948A7DF5-61C3-47A7-B5D3-4F5D89C1F30C](https://user-images.githubusercontent.com/25310886/169202421-9a7270ed-3fe2-432e-8f0c-95c9accccdd4.jpeg)

Need some placeholder text or a default sort selected so this is more obvious. If you miss the chevron it just looks like a hr

**Comment by Developing-Developer2019** [comment]
Needs contributing.md file to allow people to help with issues.

**Comment by benjaminsampica** [comment]
Hi 👋🏻 @Developing-Developer2019. Is https://github.com/benjaminsampica/DynamoLeagueBlazor#getting-started this what you’re looking for?

**Comment by Developing-Developer2019** [comment]
Ah sorry, perfect thankyou!
